### ISSUE TITLE
Issue 3: leere Maske bei nicht segmentierten BScans

### ISSUE THREAD

**Issue by Melli-W** [PhillyVanilly9119/AnteriorSegment_OctSegmentationPipeline#3]
Wenn Endothel und OVD-Schicht nicht sichtbar (manchmal in Randbereichen der Kornea der Fall) und nicht segmentiert, wird da keine Maske ausgegeben. Ist es möglich, dennoch eine "leere" Maske zu generieren, damit später bei der Auswertung keine Lücke entsteht?

**Comment by PhillyVanilly9119** [comment]
Added function saveEmptyMask() to save empty masks if no boundary layers are visible, implemented and tested the logic in mainSegmentationLoop
