### ISSUE TITLE
falsche Reihenfolge der zusätzlich erstellten Masken

### ISSUE THREAD

**Issue by Melli-W** [PhillyVanilly9119/AnteriorSegment_OctSegmentationPipeline#5]
Die Reihenfolge der zusätzlich erstellten Masken (continuousMasks und thickMasks) stimmt nicht mit der Reihenfolge der ursprünglichen Masken überein. Es scheint als wäre die Zählweise nicht richtig, wie es beim Einlesen der Masken für die Erstellung der Thickness Map schon der Fall war. Es ist ein Sprung bei jeder 10ten Maske (wie periodisches Muster).

**Comment by PhillyVanilly9119** [comment]
Loaded masks through loadMasksFromFile(), which does sort the indices in ascending order and should therefore correct for the discribed mismatch when saving the additionally calculated masks
